
def COLOUR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
    'ABORTED': 'danger',
]

pipeline {
    
    agent any 

    environment {
        // Give cluster name
        cluster = 'vproprod'
        // Give service name
        service = 'vproappprodsvc'
    }

    stages {

        stage ('Deploy to ECS Staging') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    // some block
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }

    }
    
    post {
        always {
            slackSend channel: '#devops', 
                color: COLOUR_MAP[currentBuild.currentResult], 
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at ${env.BUILD_URL}"
        }
    }

}
